name: Check Permission

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


on:
  push:
    branches:
      - main

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     
     - id: "auth"
       name: "Authenticate to GCP"
       uses: "google-github-actions/auth@v2"
       with:
          project_id: "fpt-dev"
          workload_identity_provider: "projects/871426567684/locations/global/workloadIdentityPools/github/providers/my-repo"

     - id: "gcloud"
       name: "gcloud"
       run: gcloud secrets versions access 1 --secret="k8s-secret"
        
