

name: Daily report for Copilot reviews

on:
  schedule:
    - cron: "00 10 * * *" # every day at 10:00 AM UTC - 17:00 AM Vietnam time
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fetch-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (not needed, but often standard)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Fetch PRs and send email
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_ORG }}
          ORG_NAME: Hillspire
          GMAIL_USER: hlengoc.fpt@hillspire.com
          GMAIL_PASS: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          ls
          python python-script.py
          